export { API_ENDPOINTS, ROUTES } from "./api";
export {
  SOIL_DATA,
  NUTRIENT_DATA,
  DASHBOARD_STATS,
  SOIL_MONITORING_DATA,
  SOIL_SENSOR_CARDS,
  FERTILIZER_RECOMMENDATIONS,
  DISEASE_DETECTION_RESULT,
  DISEASE_DETECTION_FEATURES,
} from "./data";
